name: Debug and Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          npm list --depth=0  # List installed packages
          
      - name: Check directory structure before build
        run: ls -la
        
      - name: Build with verbose output
        run: |
          npm run build
          echo "Build completed, checking output directory:"
          ls -la
          echo "Checking if out directory exists:"
          ls -la out || echo "out directory does not exist"
        
      - name: Debug Next.js configuration
        run: cat next.config.js
        
      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
      
      - name: Add .nojekyll file
        if: success()
        run: touch ./out/.nojekyll || echo "Could not create .nojekyll file"

      - name: Clean install
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install