name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Removed the cache option since you don't have a lock file

      - name: Install dependencies
        run: npm install
        
      - name: Generate package-lock.json for future caching
        run: npm i --package-lock-only
        
      - name: List installed packages
        run: npm list --depth=0
        
      - name: Check next.config.js
        run: cat next.config.js
        
      - name: Build project
        run: npm run build
        
      - name: Verify build output
        run: |
          echo "Checking for output directory:"
          ls -la
          if [ -d "out" ]; then
            echo "✅ 'out' directory exists"
            echo "Contents of 'out' directory:"
            ls -la out
          else
            echo "❌ 'out' directory does not exist!"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi
        
      - name: Create .nojekyll file
        run: touch out/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true
          
      - name: Print deployment status
        run: |
          echo "🚀 Deployment complete!"
          echo "Please check your repository settings to ensure GitHub Pages is configured to deploy from the gh-pages branch."